apiVersion: v1
kind: ConfigMap
metadata:
  name: turbine-server
data:
  application.yml: |
    turbine.aggregator.clusters.default: coolstore-gateway.coolstore-gateway
    turbine.aggregator.clusterConfig: default
    turbine.instanceUrlSuffix: :8080/hystrix.stream