---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "ServiceAccount"
  metadata:
    labels:
      provider: "fabric8"
      project: "turbine-server"
      version: "1.0.28"
      group: "io.fabric8.kubeflix"
    name: "turbine"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      servicepath: "/turbine.stream"
      fabric8.io/iconUrl: "img/icons/spring-boot.svg"
      fabric8.io/git-commit: "2656e3679d0034bb63c83e429f17135b30ed7d71"
      fabric8.io/git-branch: "release-v1.0.28"
    labels:
      project: "turbine-server"
      provider: "fabric8"
      version: "1.0.28"
      group: "io.fabric8.kubeflix"
      expose: "true"
    name: "turbine-server"
  spec:
    ports:
    - name: "http"
      port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "turbine-server"
      provider: "fabric8"
      group: "io.fabric8.kubeflix"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/spring-boot.svg"
      fabric8.io/git-commit: "2656e3679d0034bb63c83e429f17135b30ed7d71"
      fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=turbine-server&var-version=1.0.28"
      fabric8.io/git-branch: "release-v1.0.28"
    labels:
      project: "turbine-server"
      provider: "fabric8"
      version: "1.0.28"
      group: "io.fabric8.kubeflix"
    name: "turbine-server"
  spec:
    replicas: 1
    selector:
      project: "turbine-server"
      provider: "fabric8"
      group: "io.fabric8.kubeflix"
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: "Rolling"
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: "img/icons/spring-boot.svg"
          fabric8.io/git-commit: "2656e3679d0034bb63c83e429f17135b30ed7d71"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=turbine-server&var-version=1.0.28"
          fabric8.io/git-branch: "release-v1.0.28"
        labels:
          project: "turbine-server"
          provider: "fabric8"
          version: "1.0.28"
          group: "io.fabric8.kubeflix"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/turbine-server:1.0.28"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 180
          name: "turbine-server"
          ports:
          - containerPort: 8080
            name: "http"
          - containerPort: 8778
            name: "jolokia"
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 10
          securityContext:
            privileged: false
        serviceAccountName: "turbine"
    triggers:
    - type: "ConfigChange"
