metadata:
  labels:
    hystrix.cluster: coolstore
    hystrix.enabled: true
spec:
  template:
    metadata:
      labels:
        hystrix.cluster: coolstore
        hystrix.enabled: true
    spec:
      containers:
        - readinessProbe:
            failureThreshold: 2
            httpGet:
              path: "/health/readiness"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successTreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: "/health/liveness"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
