apiVersion: v1
kind: ConfigMap
metadata:
  name: turbine-server
data:
  application.yml: |
    turbine.aggregator.clusters.coolstore: 
    turbine.aggregator.clusterConfig: coolstore
    turbine.instanceUrlSuffix: :8080/hystrix.stream
