apiVersion: v1
kind: Template
metadata:
  name: turbine
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: turbine-server
    name: turbine-server
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.lab.example.com/fabric8/turbine-server:1.0.28
      from:
        kind: DockerImage
        name: registry.lab.example.com/fabric8/turbine-server:1.0.28
      importPolicy: {}
      name: 1.0.28
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: turbine-server
    name: turbine-server
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: turbine-server
      deploymentconfig: turbine-server
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: turbine-server
          deploymentconfig: turbine-server
      spec:
        containers:
        - image: registry.lab.example.com/fabric8/turbine-server:1.0.28
          imagePullPolicy: IfNotPresent
          name: turbine-server
          ports:
          - containerPort: 9779
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - turbine-server
        from:
          kind: ImageStreamTag
          name: turbine-server:1.0.28
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: turbine-server
    name: turbine-server
  spec:
    host: turbine.apps.lab.example.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: turbine-server
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: turbine-server
    name: turbine-server
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    - name: 9779-tcp
      port: 9779
      protocol: TCP
      targetPort: 9779
    selector:
      app: turbine-server
      deploymentconfig: turbine-server
    sessionAffinity: None
    type: ClusterIP
