metadata:
  labels:
    hystrix.cluster: default
    hystrix.enabled: true
    ribbon.eureka.enabled: false
    eureka.client.enabled: false
spec:
  template:
    metadata:
      labels:
        hystrix.cluster: default
        hystrix.enabled: true
        ribbon.eureka.enabled: false
        eureka.client.enabled: false
    spec:
      containers:
        - livenessProbe:
            failureThreshold: 2
            httpGet:
              path: "/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
          env:
            - name: CATALOG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: CATALOG_SERVICE_URL
                  name: gatewaycatalog
            - name: CART_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: CART_SERVICE_URL
                  name: gatewaycart

